### ISSUE TITLE
Not doing anything after added new Todo

### ISSUE THREAD

**Issue by peterbrinck** [StevenDevooght/cockpit-todos#1]
Every time I add a new Todo, by first pressing on the Todo icon in the top menu, and then pressing the "+" titled Add Todo, nothing happens.
When I press it, a alert box comes up, with a field to type in the Todo name - But then nothing more happens.

Why is that?
![cockpilot todo issue](https://cloud.githubusercontent.com/assets/6154068/3487595/19826dd0-048c-11e4-9746-75db88e3c8fc.gif)

**Comment by StevenDevooght** [comment]
The Query api changed in one of the latest versions of Cockpit. Should be fixed now.
